# Generated by Django 6.0.1 on 2026-01-19 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(help_text='最佳尺寸：1280*853', upload_to='news/', verbose_name='新闻图片')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '新闻列表',
                'verbose_name_plural': '新闻列表',
                'db_table': 'news',
            },
        ),
    ]
