# Generated by Django 6.0.1 on 2026-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(help_text='最佳尺寸：500*755', upload_to='avatars/', verbose_name='头像')),
                ('title', models.CharField(max_length=30, verbose_name='职务')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'db_table': 'team',
            },
        ),
    ]
