# Generated by Django 6.0.1 on 2026-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='最佳尺寸：1920*1280', upload_to='slides/', verbose_name='幻灯片图片')),
                ('title', models.CharField(help_text='一级标题', max_length=200, verbose_name='标题')),
                ('content', models.CharField(help_text='二级内容', max_length=200, verbose_name='内容')),
            ],
            options={
                'verbose_name': '幻灯片',
                'verbose_name_plural': '幻灯片',
            },
        ),
    ]
