# Generated by Django 6.0.1 on 2026-01-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
    ]
