# Generated by Django 6.0.1 on 2026-01-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_alter_slide_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '幻灯片列表', 'verbose_name_plural': '幻灯片列表'},
        ),
    ]
